site_name: ODAM
site_description: >-
  ODAM, or Operationalizing Data Analytics Methodology, is a comprehensive approach that helps organizations build a data-driven culture and achieve measurable business outcomes.
plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: true
      caption_position: bottom
  - minify:
      minify_html: true
  # - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cperkins2/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: material/format-list-bulleted
  logo: assets/odam-logo.jpeg
  favicon: assets/odam-logo.png
  features:
    - announce.dismiss
    - content.code.copy
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow
    - navigation.tracking
    - content.code.annotate
  palette: 
    scheme: odam-light

copyright: Copyright &copy; 2023 Chris Perkins

nav:
  - Home: index.md
  - 1-Data is Beautiful: data-is-beautiful/index.md
  - 2-Data Strategy Template: strategy-template/index.md
  - 3-Using ODAM to Setup Your ACE: ace/index.md
  - 4-Getting Tactical: getting-tactical/index.md
  - Conclusion: conclusion/index.md
  - About the Author: about/index.md
