site_name: ODAM
site_description: >-
  ODAM, or Operationalizing Data Analytics Methodology, is a comprehensive approach that helps organizations build a data-driven culture and achieve measurable business outcomes.
plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: true
      caption_position: bottom
  - minify:
      minify_html: true
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/odam-logo.jpeg
  favicon: assets/odam-logo.png
  features:
    - header.autohide
    # - content.action.edit
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow
    - navigation.tracking
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

copyright: Copyright &copy; 2023 Chris Perkins

nav:
  - Home: index.md
  - Data is Beautiful: 
      - Data is Beautiful: data-is-beautiful/index.md

